#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.2.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Jul 03 08:58:28 CDT 2024
# SW Build 4126759 on Thu Feb  8 23:52:05 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_12 -L axi_utils_v2_0_8 -L xbip_pipe_v3_0_8 -L xbip_dsp48_wrapper_v3_0_5 -L xbip_dsp48_addsub_v3_0_8 -L xbip_dsp48_multadd_v3_0_8 -L xbip_bram18k_v3_0_8 -L mult_gen_v12_0_20 -L floating_point_v7_1_17 -L c_reg_fd_v12_0_8 -L xbip_addsub_v3_0_8 -L c_addsub_v12_0_17 -L cordic_v6_0_21 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot example_sim_behav xil_defaultlib.example_sim xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_12 -L axi_utils_v2_0_8 -L xbip_pipe_v3_0_8 -L xbip_dsp48_wrapper_v3_0_5 -L xbip_dsp48_addsub_v3_0_8 -L xbip_dsp48_multadd_v3_0_8 -L xbip_bram18k_v3_0_8 -L mult_gen_v12_0_20 -L floating_point_v7_1_17 -L c_reg_fd_v12_0_8 -L xbip_addsub_v3_0_8 -L c_addsub_v12_0_17 -L cordic_v6_0_21 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot example_sim_behav xil_defaultlib.example_sim xil_defaultlib.glbl -log elaborate.log

